#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/shmmq
#
# IDENTIFICATION
#    src/backend/access/shmmq/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/shmmq
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = shmmqam.o 

include $(top_srcdir)/src/backend/common.mk
